= RedREST API Guide
Julien Ruaux;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-request-title: Example request
:operation-http-response-title: Example response

[[redisearch]]
== RediSearch

=== Search

The `indexes` resource is used to execute search commands `FT.CREATE`, `FT.INFO`, `FT.DROP`, and `FT.ADD`.

[[create-index]]
==== Creating an index

A `POST` request is used to create an index.

operation::create-index[snippets='request-fields,http-request,http-response']

[[get-index-info]]
==== Getting index info

A `GET` request is used to get index information.

operation::get-index-info[snippets='http-request,http-response']

[[drop-index]]
==== Dropping an index

A `DELETE` request is used to drop an index.

operation::drop-index[snippets='request-fields,http-request,http-response']

[[add-documents]]
==== Adding documents

A `POST` request is used to drop an index.

operation::add-documents[snippets='request-fields,http-request,http-response']

[[delete-documents]]
==== Deleting documents

A `DELETE` request is used to drop an index.

operation::delete-documents[snippets='http-request,http-response']


[[search]]
==== Searching

A `POST` request is used to search an index.

operation::search[snippets='request-fields,http-request,http-response']

=== Autocomplete

The `suggestions` resource is used to execute suggestion commands `FT.SUGADD` and `FT.SUGGET`.

[[add-suggestions]]
==== Adding suggestions

A `POST` request is used to add suggestions.

operation::add-suggestions[snippets='request-fields,http-request,http-response']

[[get-suggestions]]
==== Getting suggestions

A `GET` request is used to get suggestions.

operation::get-suggestions[snippets='request-parameters,http-request,http-response']
